### ISSUE TITLE
issue accessing data

### ISSUE THREAD

**Issue by jhsiao999** [jdblischak/fucci-seq#56]
User's feedback: 

```
Trying to load any of these files
	- fucci-seq/data/eset/*.rds, 
	- fucci-seq/data/eset-filtered.rds
	- fucci-seq/data/eset-final.rds
	- fucci-seq/data/eset-raw.rds
	- fucci-seq/data/intensity.rds
I get a Error in readRDS(..): unknown input format. 
The RDS fucci-seq/data/image-qc-final.rds works interestingly.

Further trying to deflate fucci-seq/fucci-counts.txt.gz, returns gzip: fucci-counts.txt.gz: not in gzip format
```

**Comment by jdblischak** [comment]
Downloading those files will require the user to have `git-lfs` installed. They can either install it directly themselves or install the conda environment (the latter is likely to large an investment for a curious user that just wants to explore a little). I have [setup instructions](https://jdblischak.github.io/singlecell-qtl/contributing.html#initial_setup) for singlecell-qtl, but these are aimed at collaborators. Would you like me to put together some instructions for installing `git-lfs`?

Another option once you are finished with this project is to also host a tarball of all the data on the giladlab website. This will make it easy for anyone to download without have to use either Git or Git LFS.

**Comment by jhsiao999** [comment]
For the first option: I think it'd be a good idea to put in instructions for those who may already have `git-lfs` or are interested in doing so. So this would work only for those who have subscription to Git Large File Storage? 

For the second option: Yes. I think this would be the preferred option. I'll start putting the data together. Have you gone through the process of uploading data to the lab website yet? 

In addition, currently I keep information on the data (how to access and which ones are raw/filtered) here: `https://jdblischak.github.io/fucci-seq/data-overview.html`. We can add the download instructions to here. Also, can you add the instruction to the README? This way the users can see the instructions soon as they open the site. Thanks!

**Comment by jdblischak** [comment]
> For the first option: I think it'd be a good idea to put in instructions for those who may already have `git-lfs` or are interested in doing so. So this would work only for those who have subscription to Git Large File Storage?

Anyone can download the files one-by-one by clicking on them through GitHub's interface. The advantage of installing `git-lfs` is that you can install every data file at once.

> For the second option: Yes. I think this would be the preferred option. I'll start putting the data together. Have you gone through the process of uploading data to the lab website yet?

It's been a long time since I uploaded data to the lab website (it was back when we hosted it on our own machine), so I don't have any advice.

> In addition, currently I keep information on the data (how to access and which ones are raw/filtered) here: `https://jdblischak.github.io/fucci-seq/data-overview.html`. We can add the download instructions to here. Also, can you add the instruction to the README? This way the users can see the instructions soon as they open the site. Thanks!

In PR #57, I've added download links and `git-lfs` installation instructions to `data-overview.html`, as well as adding some basic information to the README.

**Comment by jhsiao999** [comment]
Thanks @jdblischak. I've put the datasets analyzed in the study on the website, with Briana's assistance. The datasets are stored in TXT format and include molecule count, sample phenotypes, phenotype labels, gene information, and FUCCI intensities. See link below.

https://giladlab.uchicago.edu/wp-content/uploads/2019/02/Hsiao_et_al_2019.tar.gz

**Comment by jdblischak** [comment]
@jhsiao999 Looks good! And I'd recommend adding that link to the paper in the next round of revisions.

**Comment by dburkhardt** [comment]
Hi I'm having what appears to be a related issue. When I try to download the final batch-normalized data from the website (https://github.com/jdblischak/fucci-seq/blob/master/data/eset-final.rds?raw=true), I get the following error when I try to load it:
```R
> load("~/Downloads/eset-final.rds")
Error in load("~/Downloads/eset-final.rds") : 
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file 'eset-final.rds' has magic number 'X'
  Use of save versions prior to 2 is deprecated
```

Any idea why this isn't working? The website says that link should work...

**Comment by dburkhardt** [comment]
Ahh I see, I didn't realize I need to run:

```R
eset <- Reduce(combine, Map(readRDS, Sys.glob("data/eset/*.rds")))
```
 to load the data

**Comment by jdblischak** [comment]
@dburkhardt The key is to use `readRDS()` to import the `*.rds` files. The function `load()` is for `*.RData` files.

I don't recommend using the `Reduce()/combine()` strategy because that is slow. It requires both loading and merging the data sets.

Try directly loading the final data set by running the line below.

```
eset_final <- readRDS("~/Downloads/eset-final.rds")
```
