### ISSUE TITLE
Continuous to discrete cc label

### ISSUE THREAD

**Issue by rfechtner** [jdblischak/fucci-seq#60]
In Figure 2B you provide a schematic overview on how the Fucci intensities correlate to the "classical" discrete cell cycle phases through the theta value. 
It suggests that a theta of: 

0 - pi/2 -> M
pi/2 - pi -> G1
pi - 3pi/2 -> S
3pi/2 - 2pi -> G2M

Would you say that these boundaries can be used in order to challenge other CC-Classifier (such as Seurat) or are the boundaries rather in between those values. If later what boundaries would you suggest. My aims is to assign a discrete cell cycle label to every cell of your dataset based on the Fucci Intensities (or theta).

**Comment by jhsiao999** [comment]
@rfechtner Sorry for the late response. 

We added cell cycle phase boundaries in Figure 2B to help interpreting cyclic trend of gene expression. I do not suggest using these boundaries to classify cells into discrete cell cycle phase. 

Instead, some possible ideas might be clustering the cells based on theta - this would require taking account into the circular nature of theta, or clustering the cells based on the top cyclic genes with respect to theta. I am also happy to discuss any suggestions and ideas that you might have. 

Joyce

**Comment by rfechtner** [comment]
@jhsiao999 no worries and thank you for the reply. I will have a look. 

In the meantime I will close this issue, as the initial question is thereby answered :) 

Cheers 
Ron
