### ISSUE TITLE
Questions about the raw fastq data in GSE121265

### ISSUE THREAD

**Issue by apredeus** [jdblischak/fucci-seq#62]
Hello John, 

I'm trying to reprocess the raw data from the publication (deposited in GSE121265), and I was wondering if you could comment on the library structure or the location of the scripts used for raw read alignment/quantification. 

The questions I have are

- are reads meant to be 50 bp single-end reads? (fastq to SRA conversion often does terrible things to scRNA-seq reads)
- does one fastq correspond to one cell? if so, have they been demultiplexed before being deposited in the SRA? 
- where in the read is the UMI located? 

Thank you very much in advance!

**Comment by jdblischak** [comment]
Hi @apredeus! Please see below for answers to your questions:

> the location of the scripts used for raw read alignment/quantification

The FASTQ to gene counts conversion was done using this [Snakefile](https://github.com/jdblischak/fucci-seq/blob/master/Snakefile). However, the input was the FASTQ files per sample per sequencing lane. The FASTQ files deposited on GEO are all the reads per sample combined across the various sequencing lanes. Thus you'd have to delete the rule `combine_fastq` (and also organize and rename the files). Though I wouldn't recommend that you re-run the exact same pre-processing code that we've already ran. We already provide the processed counts that you could use directly (see the [data overview page](https://jdblischak.github.io/fucci-seq/data-overview.html)). They're also available directly from GEO: [eset-raw.rds](https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE121265&format=file&file=GSE121265%5Feset%2Draw%2Erds%2Egz) contains the raw RNA-seq counts for all the samples, and [eset-final.rds](https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE121265&format=file&file=GSE121265%5Feset%2Dfinal%2Erds%2Egz) contains the counts for the samples and genes that passed the quality filters. I would only invest time in re-processing the FASTQ files if you want to use your own preferred combination of tools.

> are reads meant to be 50 bp single-end reads?

Yes, they're 50 bp single-end. It's frustrating that the GEO website doesn't display this somewhere prominently. I provided this information during the GEO submission process, which I confirmed by checking [`data/geo-raw.txt`](https://github.com/jdblischak/fucci-seq/blob/master/data/geo-raw.txt)

> does one fastq correspond to one cell?

Each FASTQ file corresponds to a single well of a Fluidigm C1 chip. Each well typically contains one intact cell, but of course they occasionally contain doublets or a lysed cell. We performed [quality control](https://jdblischak.github.io/fucci-seq/index.html#rna-seq-data-preprcessing) and report the list of [quality cells](https://github.com/jdblischak/fucci-seq/blob/master/data/quality-single-cells.txt) that we used for the analysis.

> if so, have they been demultiplexed before being deposited in the SRA?

I wouldn't use the word "demultiplexed" to describe this process. The Fluidigm C1 chip is a microfluidic technology. It can't process thousands of samples simultaneously like is done with droplet-based techniques (e.g. 10X). You are supposed to only put one sample in each chip (96 wells). However, we improved on this (ie reduced technical batch effects) by mixing cells from two individuals into each plate, and then identified each cell by the exonic SNPs detected in the RNA-seq reads.

The name of each FASTQ files corresponds to CHIP-WELL-INDIVIDUAL. For example, the file labelled [20170905-A01-NA18870](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3429004) refers to a cell from individual NA18870 in well A01 of the chip 20170905 (we used the date format YYYYMMDD to refer to each chip).

These libraries was sequenced on more than one lane, but all the reads were combined into this one FASTQ file.

> where in the read is the UMI located?

The UMI is 6 bp long and located on the 5' end of each read. The UMI is immediately followed by 3-4 G's. For more details, you can read the original UMI protocol described in [Islam et al. 2014](https://pubmed.ncbi.nlm.nih.gov/24363023/).

Here is the code we used to extract the UMI from each read:

https://github.com/jdblischak/fucci-seq/blob/8f88d99cbe45fed169632d53ef4b1483feff8848/Snakefile#L229-L236

**Comment by apredeus** [comment]
Thank you so much for your detailed answer! This is great. Unfortunately, for my purposes I would need to re-align the reads, but your answers make it fairly straightforward. 

Thanks again!
